### PR TITLE
fix RoutedViewHost and ViewModelViewHost to allow DefaultContent

### LINKED ISSUE #2815: [BUG] WPF - ViewModelViewHost and RoutedViewHost not displaying DefaultContent
**Describe the bug**
ViewModelViewHost and RoutedViewHost do not display default content on WPF platform for not set ViewModel or not-performed initial navigation.

**Steps To Reproduce**
Add ViewModelViewHost or RoutedViewHost to Window, add default content, do not set anything else.

**Expected behavior**
I expect the default content to be shown for RoutedViewHost and ViewModelViewHost when no viewmodel is set or navigation has been performed.

**Screenshots**
Instead of the screenshot here is a minimal repro - both working, and not working.
[rx-repro.zip](https://github.com/reactiveui/ReactiveUI/files/6735737/rx-repro.zip)

**Environment**
- OS: Windows
- Version: 14.1.1, basically 9.8.9
- Platform: WPF

**Additional context**
For ViewModelViewHost this [broke from 9.8.1 to 9.8.9](https://github.com/reactiveui/ReactiveUI/compare/9.8.1..9.8.9)
In case of RoutedViewHost: This is broken since atleast release 8.0.0.

### PR DESCRIPTION
**Pull request by ChrisPulman**
Refactored RoutedViewHost and ViewModelViewHost to allow DefaultContent to be shown

fixes #2815

**What kind of change does this PR introduce?**

fix 

**What is the current behaviour?**

DefaultContent is not displayed for RoutedViewHost and ViewModelViewHost when loaded with null ViewModel

**What is the new behaviour?**

DefaultContent is displayed for RoutedViewHost and ViewModelViewHost when loaded with null ViewModel

**What might this PR break?**

Content will have a value when previously may not have depending upon the version of ReactiveUI i.e. >9.8.9

**Please check if the PR fulfils these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

File: src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs [hunk 1]
```diff
@@ -55,6 +58,8 @@ class RoutedViewHost : TransitioningContentControl, IActivatableView, IEnableLog
         public static readonly DependencyProperty ViewContractObservableProperty =
             DependencyProperty.Register("ViewContractObservable", typeof(IObservable<string>), typeof(RoutedViewHost), new PropertyMetadata(Observable<string>.Default));
 
+        private string? _viewContract;
```
Comment (glennawatson) [inline src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs:61]: Seems like you aren't setting this anywhere?

Comment (ChrisPulman) [reply src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs:61]: Thanks, I will fix that before going to sleep.

Comment (ChrisPulman) [reply src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs:61]: Updated

**Review by glennawatson — APPROVED** [review]
