### PR TITLE
Fix WPF design-time activation and main-thread bindings

### LINKED ISSUE #4332: [Bug]: XDG0003 errors with WPF designer (regression)
### Describe the bug 🐞

With RxUI 23.2.1 opening a XAML file with user controls produces XDG0003 errors "Don't know how to detect when UtilityTemplate.ConveyorView is activated/deactivated, you may need to implement IActivationForViewFetcher", and the user control content isn't shown. This doesn't happen with RxUI 22.3.1.

### Step to reproduce

[XDG0003.zip](https://github.com/user-attachments/files/26680050/XDG0003.zip)

Build the attached project, open ShellView.xaml and switch to the Design tab.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Should behave as per RxUI 22.3.1.

### Screenshots 🖼️

_No response_

### IDE

_No response_

### Operating system

Windows

### Version

11

### Device

_No response_

### ReactiveUI Version

23.2.1

### Additional information ℹ️

_No response_

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

Fixes #4332 

**What is the current behavior?**

#4332

**What is the new behavior?**

## Summary

This PR resolves several WPF initialization, binding, and design-time activation issues in ReactiveUI.

### Changed

- Updated the ReactiveUI builder flow so WPF applications can use `Build()` to receive the same initialization behavior previously tied to `BuildApp()`.
- Ensured WPF registrations are applied through the builder path used by `ReactiveUI.Builder.WpfApp`.
- Fixed WPF command binding behavior that could throw cross-thread exceptions.
- Fixed WPF `ComboBox.SelectedItem` two-way binding behavior so selected item updates propagate correctly.
- Added design-time handling for `WhenActivated` so WPF views loaded by the Visual Studio XAML designer do not throw:
  `Don't know how to detect when ... is activated/deactivated, you may need to implement IActivationForViewFetcher`
- Preserved runtime behavior for missing activation fetchers while allowing true designer-mode loading to continue safely.
- Added WPF tests covering command rebinding, property binding, ComboBox selected item binding, and design-mode activation behavior.
- Updated API approval baselines for the builder changes.

## Validation

- Built `ReactiveUI.Wpf` across all target frameworks.
- Built `ReactiveUI.Builder.WpfApp` for `net481`.
- Ran WPF test matrix successfully:
  - `net8.0-windows10.0.19041.0`: 327 passed
  - `net9.0-windows10.0.19041.0`: 326 passed
  - `net10.0-windows10.0.19041.0`: 326 passed
- Ran full solution build successfully after restore:
  - `0 errors`
  - Existing duplicate `TUnit` package reference warning remains in `ReactiveUI.Builder.Tests`.

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

File: src/ReactiveUI/Activation/ViewForMixins.cs [hunk 1]
```diff
@@ -224,6 +232,35 @@ public static IDisposable WhenActivated(this IActivatableView item, Action<Compo
...
+    /// <param name="item">The view being activated.</param>
+    /// <returns><see langword="true"/> when the current context is design mode; otherwise, <see langword="false"/>.</returns>
+    private static bool IsInDesignMode(object item)
+    {
+        if (LicenseManager.UsageMode == LicenseUsageMode.Designtime)
+        {
+            return true;
+        }
+
+        var dependencyObjectType = Type.GetType("System.Windows.DependencyObject, WindowsBase", throwOnError: false);
```
Comment (glennawatson) [inline src/ReactiveUI/Activation/ViewForMixins.cs]: Move this reflection piece out of the main rxui assembly into the WPF one if you can. Maybe an interface or something.

File: src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs [hunk 2]
```diff
@@ -517,6 +517,57 @@ public IDisposable BindTo<TValue, TTarget, TTValue>(
...
+    private static IObservable<bool> ScheduleOnMainThreadIfRequired<TView>(TView view, bool value)
+        where TView : class
+    {
+        var dispatcher = GetDispatcher(view);
+        if (dispatcher is null || IsDispatcherAccessAvailable(view))
+        {
+            return Observable.Return(value);
+        }
+
+        return Observable.Create<bool>(observer =>
```
Comment (glennawatson) [inline src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs]: Move out to the WPF repo

**Review by glennawatson — CHANGES_REQUESTED** [review]

**Review by glennawatson — APPROVED** [review]
