### PR TITLE
fix: Fix android crashing on text binding

### LINKED ISSUE #2170: [BUG] PropertyBindingMixins.Bind crashes
**Describe the bug**
`ReactiveUI.PropertyBindingMixins.Bind` throws `android.runtime.JavaProxyThrowable: System.Reflection.TargetParameterCountException: Parameter count mismatch.`

**Steps To Reproduce**
1. Create new Xamarin.Android project;
2. Add layout with TextView;
3. Invoke `ReactiveUI.PropertyBindingMixins.Bind` inside activity to bind `TextView.Text` with ViewModel for example:
```
this.Bind(
                ViewModel,
                x => x.ImportantText,
                x => x.SuperTextView.Text);
```
4. Launch app on device;
5. Observe crash.

**Expected behavior**
No crash

**Stacktrace**
```
09-18 13:00:36.914 E/AndroidRuntime(12346): FATAL EXCEPTION: main
09-18 13:00:36.914 E/AndroidRuntime(12346): Process: ReaciveUITest.ReaciveUITest, PID: 12346
09-18 13:00:36.914 E/AndroidRuntime(12346): android.runtime.JavaProxyThrowable: System.Reflection.TargetParameterCountException: Parameter count mismatch.
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) [0x000ee] in <ff07eae8184a40a08e79049bbcb31a0e>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) [0x00000] in <ff07eae8184a40a08e79049bbcb31a0e>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.ReflectionUtils.CreateDelegate[TDelegate] (System.Object o, System.Reflection.MethodInfo method) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.FromEvent`2[TDelegate,TEventArgs].GetHandler (System.Action`1[T] onNext) [0x00025] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.EventProducer`2+Session[TDelegate,TArgs].Initialize () [0x00023] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.EventProducer`2+Session[TDelegate,TArgs].Connect (System.IObserver`1[T] observer) [0x00021] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346): --- End of stack trace from previous location where exception was thrown ---
09-18 13:00:36.914 E/AndroidRuntime(12346): 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.ExceptionHelpers.Throw (System.Exception exception) [0x0000a] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Stubs+<>c.<.cctor>b__2_1 (System.Exception ex) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.AnonymousSafeObserver`1[T].OnError (System.Exception error) [0x00010] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Subjects.Subject`1[T].OnError (System.Exception error) [0x00065] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Merge`1+Observables+_+InnerObserver[TSource].OnError (System.Exception error) [0x00016] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.914 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnError (System.Exception error) [0x0002f] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].OnError (System.Exception error) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.EventProducer`2+Session[TDelegate,TArgs].Connect (System.IObserver`1[T] observer) [0x0003e] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.EventProducer`2[TDelegate,TArgs].Run (System.IObserver`1[T] observer) [0x00027] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.BasicProducer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00052] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.915 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.TailRecursiveSink`1[TSource].Drain () [0x00120] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.TailRecursiveSink`1[TSource].Run (System.Collections.Generic.IEnumerable`1[T] sources) [0x00018] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Concat`1[TSource].Run (System.Reactive.Linq.ObservableImpl.Concat`1+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnNext (System.IObservable`1[T] value) [0x00052] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult].OnNext (TSource value) [0x00021] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[TSource].OnNext (TSource value) [0x00029] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.IdentitySink`1[T].OnNext (T value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource].LoopRec (System.Reactive.Concurrency.IScheduler scheduler) [0x00085] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_+<>c[TSource].<Run>b__3_0 (System.Reactive.Concurrency.IScheduler innerScheduler, System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource] this) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState] (TState state, System.Func`3[T1,T2,TResult] action) [0x00014] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource].Run (System.Collections.Generic.IEnumerable`1[T] source, System.Reactive.Concurrency.IScheduler scheduler) [0x00018] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1[TSource].Run (System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.TailRecursiveSink`1[TSource].Drain () [0x00120] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.TailRecursiveSink`1[TSource].Run (System.Collections.Generic.IEnumerable`1[T] sources) [0x00018] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Concat`1[TSource].Run (System.Reactive.Linq.ObservableImpl.Concat`1+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.917 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource].OnNext (System.IObservable`1[T] value) [0x00052] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult].OnNext (TSource value) [0x00021] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1[TSource].Run (System.IObserver`1[T] observer) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.BasicProducer`1[TSource].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00052] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1[TSource].Run (System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Switch`1[TSource].Run (System.Reactive.Linq.ObservableImpl.Switch`1+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.918 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Where`1+Predicate[TSource].Run (System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[TSource] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2[TSource,TKey].Run (System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2+_[TSource,TKey] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Sink`2[TSource,TTarget].Run (System.IObservable`1[T] source) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Select`2+Selector[TSource,TResult].Run (System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[TSource,TResult] sink) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Producer`2[TTarget,TSink].SubscribeRaw (System.IObserver`1[T] observer, System.Boolean enableSafeguard) [0x00060] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.ObservableExtensions.SubscribeSafe[T] (System.IObservable`1[T] source, System.IObserver`1[T] observer) [0x00036] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.Merge`1+Observables+_[TSource].OnNext (System.IObservable`1[T] value) [0x00013] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Sink`1[TTarget].ForwardOnNext (TTarget value) [0x00000] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.919 E/AndroidRuntime(12346):   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1+_[TSource].LoopRec (System.Reactive.Concurrency.IScheduler scheduler) [0x00085] in <f9e209095f5a4628a0b7a00d8a83c3b9>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at ReactiveUI.PropertyBinderImplementation.BindImpl[TViewModel,TView,TVMProp,TVProp,TDontCare] (TViewModel viewModel, TView view, System.Linq.Expressions.Expression`1[TDelegate] vmProperty, System.Linq.Expressions.Expression`1[TDelegate] viewProperty, System.IObservable`1[T] signalViewUpdate, ReactiveUI.PropertyBinderImplementation+OutFunc`2[T1,T2] vmToViewConverter, ReactiveUI.PropertyBinderImplementation+OutFunc`2[T1,T2] viewToVmConverter) [0x001d9] in <c85e2deedba740d5bf58b3f29bb2d97a>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at ReactiveUI.PropertyBinderImplementation.Bind[TViewModel,TView,TVMProp,TVProp,TDontCare] (TViewModel viewModel, TView view, System.Linq.Expressions.Expression`1[TDelegate] vmProperty, System.Linq.Expressions.Expression`1[TDelegate] viewProperty, System.IObservable`1[T] signalViewUpdate, System.Object conversionHint, ReactiveUI.IBindingTypeConverter vmToViewConverterOverride, ReactiveUI.IBindingTypeConverter viewToVMConverterOverride) [0x0008c] in <c85e2deedba740d5bf58b3f29bb2d97a>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at ReactiveUI.PropertyBindingMixins.Bind[TViewModel,TView,TVMProp,TVProp] (TView view, TViewModel viewModel, System.Linq.Expressions.Expression`1[TDelegate] vmProperty, System.Linq.Expressions.Expression`1[TDelegate] viewProperty, System.Object conversionHint, ReactiveUI.IBindingTypeConverter vmToViewConverterOverride, ReactiveUI.IBindingTypeConverter viewToVMConverterOverride) [0x00000] in <c85e2deedba740d5bf58b3f29bb2d97a>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at ReaciveUITest.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000b6] in <97283fa6d65c4572be600e1b45bc88f2>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <b62c3fba3fe848f3bb323dbe33464223>:0 
09-18 13:00:36.922 E/AndroidRuntime(12346):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.6(intptr,intptr,intptr)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at md5ac7f87ef6c593a0c21ac7e6bba13fd95.MainActivity.n_onCreate(Native Method)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at md5ac7f87ef6c593a0c21ac7e6bba13fd95.MainActivity.onCreate(MainActivity.java:29)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.Activity.performCreate(Activity.java:7088)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.Activity.performCreate(Activity.java:7079)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.os.Looper.loop(Looper.java:176)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
09-18 13:00:36.922 E/AndroidRuntime(12346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Environment**
- OS:       Android
- Version   8.1.0
- Device:   Xiaomi Redmi 5 Plus
- ReactiveUI Version: 10.1.7

### PR DESCRIPTION
**Pull request by glennawatson**
**What kind of change does this PR introduce?**

This fixes a bug where android text binding would crash.

It fixes #2170 

**What is the current behavior?**

It crashes on binding.

**What is the new behavior?**

It doesn't crash.

### CODE REVIEW

File: src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs [hunk 1]
```diff
@@ -142,10 +142,14 @@ private static DispatchItem CreateTimePickerMinuteFromWidget()
                 {
                     var view = (TView)x;
 
-                    return Observable.FromEvent<EventHandler<TEventArgs>, TEventArgs>(
```
Comment (glennawatson) [inline src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs:145]: This was the cause of the error. The event handlers weren't being set properly.

File: src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs [hunk 2]
```diff
@@ -596,30 +596,30 @@ object SetThenGet(object paramTarget, object paramValue, object[] paramParams)
...
 
                 if (isVm)
                 {
                     if (!vmToViewConverter(vmValue, out TVProp vmAsView) || EqualityComparer<TVProp>.Default.Equals(vValue, vmAsView))
                     {
-                        return null;
+                        return (false, null, false);
                     }
 
-                    return Tuple.Create((object)vmAsView, isVm);
```
Comment (glennawatson) [inline src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:614]: This is just syntactic sugar to remove a Tuple instance for the more efficient ValueTuple.

File: src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs (hunk 1 above)
Comment (glennawatson) [reply src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs:145]: Essentially, there was a mismatch between the EventHandler and Rx would cause an exception.

Now we are explicitly specifying the event handler method which is more efficient since it avoids reflection anyway.
