### PR TITLE
fix IsExecuting and Can Execute threading issue

### LINKED ISSUE #2834: [BUG] ReactiveCommand.IsExecuting does not work when outputScheduler is RxApp.TaskpoolScheduler
### Problem
```cs
var command = ReactiveCommand.CreateFromTask(
    cancellationToken => RunAsync(cancellationToken),
    outputScheduler: RxApp.TaskpoolScheduler);
command.IsExecuting
    .Subscribe(static value => 
    {
        Console.WriteLine($"IsExecuting: {value}");
    });
```
This code does not output anything to the console when the command starts and ends, only on initialization.
If I don't set the outputScheduler then everything works fine.

### Environment
ReactiveUI 13.3.2

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

fix #2834

**What is the current behaviour?**

Executing fails if a TaskPool thread is selected

**What is the new behaviour?**

Executing works if a TaskPool thread is selected

**What might this PR break?**

none expected

**Please check if the PR fulfils these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

File: src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs [hunk 1]
```diff
@@ -689,10 +688,11 @@ public class ReactiveCommand<TParam, TResult> : ReactiveCommandBase<TParam, TRes
                 }).StartWith(false).CombineLatest(_isExecuting, (canEx, isEx) => canEx && !isEx)
                 .DistinctUntilChanged()
                 .Replay(1).RefCount();
+
             _results = _synchronizedExecutionInfo.Where(x => x.Demarcation == ExecutionDemarcation.Result)
                 .Select(x => x.Result);
 
-            _canExecuteSubscription = _canExecute.Subscribe(OnCanExecuteChanged);
+            _canExecuteSubscription = _canExecute.ObserveOn(RxApp.MainThreadScheduler).Subscribe(OnCanExecuteChanged);
         }
```
Comment (glennawatson) [inline src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs:696]: This needs to be configurable and not the default due to performance.

**Review by glennawatson — CHANGES_REQUESTED** [review]
Change to be configurable

File: src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs (hunk 1 above)
Comment (ChrisPulman) [reply src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs]: added canExecuteScheduler parameter defaulted to RxApp.MainThreadScheduler

**Review by glennawatson — APPROVED** [review]
