### PR TITLE
Fix Bug #2382 DelayChangeNotifications does not delay PropertyChanged events

### LINKED ISSUE #2382: [BUG] DelayChangeNotifications does not delay PropertyChanged events
**Describe the bug**
The `ReactiveObject.DelayChangeNotifications()` method does not delay the firing of `PropertyChanged` events. (Please note `ReactiveObject.SuppressChangeNotifications()` does suppress them.)

**Steps To Reproduce**
The following C# console app demonstrates the bug. All assertions are expected to pass, but 2 of 3 fail.
```csharp
using System.Diagnostics;
using ReactiveUI;

class Example : ReactiveObject
{
    private int _value;

    public int Value
    {
        get => _value;
        set => this.RaiseAndSetIfChanged(ref _value, value);
    }
}

class Program
{
    static void Main(string[] args)
    {
        var obj = new Example();
        var changeEvents = 0;
        obj.PropertyChanged += (s, e) => changeEvents++;
        using (obj.DelayChangeNotifications())
        {
            obj.Value = 1;
            obj.Value = 2;
            Debug.Assert(changeEvents == 0, "Property change raised during delay");
        }
        Debug.Assert(changeEvents < 2, "Property change not deduped");
        Debug.Assert(changeEvents != 0, "Property change not raised");
    }
}
```

**Expected behavior**
Similar to how `ReactiveObject.SuppressChangeNotifications()` affects property changed events and `ReactiveObject.DelayChangeNotifications()` delays and removes duplicate change events from the `ReactiveObject.Changed` observable. I expect:

1. No property changing and changed events will be raised between the call of `ReactiveObject.SuppressChangeNotifications()` and the disposing of the returned `IDisposable`.
2. When the `IDisposable` is disposed of, any delayed changing and changed events will be raised
3. Changing and changed events that are delayed will be deduplicated so that if a property is changed more than once during the delayed time, only one property change event will be raised for it.

**Environment**
- OS:       Windows Pro
- Version   10.0.18363
- Device:   Dell Vostro 7590
- ReactiveUI: v11.3.1
- .NET Framework: v4.7.2

### PR DESCRIPTION
**Pull request by WalkerCodeRanger**
**What kind of change does this PR introduce?**
Fixes #2382 DelayChangeNotifications does not delay PropertyChanged events

**What is the current behavior?**
Calling `DelayChangeNotifications()` on a `ReactiveObject` delays the `Changing` and `Changed` observable notifications, but not the actual `PropertyChanging` and `PropertyChanged` events.

**What is the new behavior?**
`DelayChangeNotifications()` now delays `PropertyChanging` and `PropertyChanged` events the same as the observables. Duplicate events are also removed the same as with the observables.

**What might this PR break?**
*Code relying on the current behavior of `PropertyChanging` and `PropertyChanged` events not being delayed.*

While I don't think this will break stuff, the most likely places for other bugs to be introduced:

* Exception handling for exceptions thrown from `PropertyChanging` and `PropertyChanged` events
* The ordering of change notifications in the `Changing` and `Changed` observables
* The raising of `PropertyChanging` and `PropertyChanged` events

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
  * API docs for `DelayChangeNotifications()` was already not very specific, so didn't need to change.

**Other Information**:
The approach used here was discussed in issue #2382. See specifically [my comment](https://github.com/reactiveui/ReactiveUI/issues/2382#issuecomment-619299798) and those follow.

### CODE REVIEW

File: src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs [hunk 1]
```diff
@@ -48,12 +48,22 @@ private interface IExtensionState<out TSender>
             /// </summary>
             IObservable<Exception> ThrownExceptions { get; }
 
+            /// <summary>
+            /// sdfsdg.
```
Comment (glennawatson) [inline src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:52]: We probably want a real comment here

File: src/ReactiveUI/ReactiveObject/ReactiveObject.cs [hunk 2]
```diff
@@ -29,14 +33,54 @@ public ReactiveObject()
...
+                _propertyChanged += value;
+            }
+            remove => _propertyChanged -= value;
+        }
+
+        [SuppressMessage(
+            "StyleCop.CSharp.NamingRules",
+            "SA1300:Element should begin with upper-case letter",
+            Justification = "Event is private backing field for PropertyChanging")]
+        private event PropertyChangingEventHandler _propertyChanging;
```
Comment (glennawatson) [inline src/ReactiveUI/ReactiveObject/ReactiveObject.cs:77]: Probably best to stick to the naming scheme regardless if it's private.

File: src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs (hunk 1 above)
Comment (WalkerCodeRanger) [reply src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:52]: I absolutely agree. That was an oversight on my part. Sorry about that. I'll fix this one and the other one below.

**Comment by glennawatson** [comment]
I'll have a full review over the next hour or so. Thanks for submitting the pr

**Comment by glennawatson** [comment]
Ok, tested your changes they look good. One you fix up those comments/style issues we are good to go :)

**Comment by WalkerCodeRanger** [comment]
All the code review comments have been addressed.

**Comment by glennawatson** [comment]
I'll push out a new version later today. Thanks again.

**Comment by WalkerCodeRanger** [comment]
Great, thank you for being very responsive and helpful.
