### PR TITLE
fix: Combobox not updating when using Bind() generated ViewModelViewHost

### LINKED ISSUE #1905: [BUG] View Location does not set ComboBox.SelectionBoxItemTemplate
**Describe the bug**
View Location does not set `ComboBox.SelectionBoxItemTemplate`, while `ComboBox.ItemTemplate` is set properly.

**Steps To Reproduce**
1. Create a `ViewModel` class.
2. Create a `View` class that derives from `ReactiveUserControl<ViewModel>`.
3. Create a list of `ViewModel`-s (`List<ViewModel> viewModelsList`).
4. Put a `ComboBox comboBox` in a new window.
5. Set `comboBox.ItemsSource =  viewModelsList`.
6. Run.
7. Select an item from `comboBox` dropdown list.
8. Selected item is not shown in the SelectionBox.

**Expected behavior**
Selected item should be shown it the SelectionBox using the same template that is used for the items in the dropdown list.

**Screenshots**
image

**Environment:**
 - OS: Windows 10
 - ReactiveUI version: 9.8.1
- GUI framework: WPF

### PR DESCRIPTION
**Pull request by glennawatson**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This fixes #1905 -- where a combobox does not correctly update in WPF if the combobox item is selected.

**What is the current behavior? (You can also link to an open issue here)**

The boxes remain empty.

**What is the new behavior (if this is a feature change)?**
Due to the fact Combobox item's are cloned when they become the main view item, WhenActivated events wouldn't be fired correctly. Now also include "IsHitTestEnabled" in the list of included events we monitor.

Also changed so the ViewModelViewHost doesn't rely on the RxUI binding which can potentially give some performance boosts but also might reduce memory leak potential.

**What might this PR break?**
Hopefully nothing.

### CODE REVIEW

File: src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs [hunk 1]
```diff
@@ -27,22 +28,22 @@ namespace ReactiveUI
     public class ViewModelViewHost : TransitioningContentControl, IViewFor, IEnableLogger, IDisposable
     {
         /// <summary>
-        /// The view model dependency property.
+        /// The default content dependency property.
         /// </summary>
-        public static readonly DependencyProperty ViewModelProperty =
-            DependencyProperty.Register("ViewModel", typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null, SomethingChanged));
+        public static readonly DependencyProperty DefaultContentProperty =
+            DependencyProperty.Register("DefaultContent", typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null));
```
Comment (gpriaulx) [inline src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs]:
```suggestion
            DependencyProperty.Register(nameof(DefaultContent), typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null));
```

File: src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs [hunk 2]
```diff
@@ -27,22 +28,22 @@ namespace ReactiveUI
...
 
         /// <summary>
-        /// The default content dependency property.
+        /// The view model dependency property.
         /// </summary>
-        public static readonly DependencyProperty DefaultContentProperty =
-            DependencyProperty.Register("DefaultContent", typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null, SomethingChanged));
+        public static readonly DependencyProperty ViewModelProperty =
+            DependencyProperty.Register("ViewModel", typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null, SomethingChanged));
```
Comment (gpriaulx) [inline src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs]:
```suggestion
            DependencyProperty.Register(nameof(ViewModel), typeof(object), typeof(ViewModelViewHost), new PropertyMetadata(null, SomethingChanged));
```

File: src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs [hunk 3]
```diff
@@ -27,22 +28,22 @@ namespace ReactiveUI
...
 
         /// <summary>
         /// The view contract observable dependency property.
         /// </summary>
         public static readonly DependencyProperty ViewContractObservableProperty =
-            DependencyProperty.Register("ViewContractObservable", typeof(IObservable<string>), typeof(ViewModelViewHost), new PropertyMetadata(Observable<string>.Default));
+            DependencyProperty.Register("ViewContractObservable", typeof(IObservable<string>), typeof(ViewModelViewHost), new PropertyMetadata(Observable<string>.Default, SomethingChanged));
```
Comment (gpriaulx) [inline src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs]:
```suggestion
            DependencyProperty.Register(nameof(ViewContractObservable), typeof(IObservable<string>), typeof(ViewModelViewHost), new PropertyMetadata(Observable<string>.Default, SomethingChanged));
```
